import type { KernelRequest } from './types';
import type { KernelToolContext, KernelToolName, KernelToolResult } from './tool-registry';

function lower(text: string) { return text.toLowerCase(); }
function extractDateTimeStrings(text: string): string[] { return text.match(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d{3})?)?(?:Z|[+-]\d{2}:\d{2})?/g) ?? []; }
function inferTodayWindow() { const now = new Date(); const start = new Date(now); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1); return { timeMin: start.toISOString(), timeMax: end.toISOString() }; }
function inferSearchWindow(text: string) { const normalized = lower(text); if (normalized.includes('today')) return inferTodayWindow(); const now = new Date(); if (normalized.includes('tomorrow')) { const start = new Date(now); start.setDate(start.getDate() + 1); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1); return { timeMin: start.toISOString(), timeMax: end.toISOString() }; } if (normalized.includes('this week') || normalized.includes('next 7 days')) { const start = new Date(now); const end = new Date(now); end.setDate(end.getDate() + 7); return { timeMin: start.toISOString(), timeMax: end.toISOString() }; } return { timeMin: undefined, timeMax: undefined }; }
function inferCreatePayload(text: string): { title: string; start?: string; end?: string; description?: string; location?: string } { const trimmed = text.trim(); const dateTimes = extractDateTimeStrings(trimmed); const title = trimmed.replace(/create (a )?(calendar )?(meeting|event)/i, '').replace(/for\s+\d{4}-\d{2}-\d{2}.*/i, '').replace(/\s+/g, ' ').trim() || 'New event'; let start: string | undefined; let end: string | undefined; if (dateTimes[0]) start = new Date(dateTimes[0]).toISOString(); if (dateTimes[1]) end = new Date(dateTimes[1]).toISOString(); if (start && !end) { const next = new Date(start); next.setHours(next.getHours() + 1); end = next.toISOString(); } return { title, start, end }; }

async function callJson<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) }, cache: 'no-store' }); const payload = await response.json().catch(() => ({})); if (!response.ok) { const message = typeof (payload as any)?.message === 'string' ? (payload as any).message : typeof (payload as any)?.error === 'string' ? (payload as any).error : `Request failed (${response.status})`; throw new Error(message); } return payload as T; }

type GmailStatusPayload = { connected?: boolean; status?: string; accountEmail?: string | null; permissions?: string[]; lastSyncedAt?: string | null; emailsAnalyzed?: number; subscriptionsFound?: number; recurringPaymentsFound?: number; monthlyTotal?: number; estimatedMonthlySavings?: number; summary?: string; errorMessage?: string | null };

function extractMemoryNotes(text: string): string[] { const notes: string[] = []; const trimmed = text.trim(); const patterns = [/remember this[:\s]+(.+)/i, /save this[:\s]+(.+)/i, /note that[:\s]+(.+)/i, /my goal is[:\s]+(.+)/i, /i prefer[:\s]+(.+)/i]; for (const pattern of patterns) { const match = trimmed.match(pattern); if (match?.[1]) notes.push(match[1].trim()); } if (!notes.length && /kivo|personal ai os|project|goal|prefer|memory/i.test(trimmed)) notes.push(trimmed.slice(0, 260)); return Array.from(new Set(notes.filter(Boolean))).slice(0, 6); }

export async function runMemorySearchTool(request: KernelRequest, context: KernelToolContext): Promise<KernelToolResult> { const text = lower(request.message); const projectHints = ['Kivo is the user’s Personal AI OS / operator-style AI project.', 'Current active agent path is src/agent/kernel via runKernelStream.', 'Important product direction: make Memory, Gmail, and Calendar useful together.']; const relevant = projectHints.filter((hint) => text.includes('kivo') || text.includes('project') || text.includes('agent') || text.includes('memory') || text.includes('context')); return { tool: 'memory.search', ok: true, summary: relevant.length ? `Found ${relevant.length} relevant project memory note${relevant.length === 1 ? '' : 's'}.` : 'Checked available project memory context.', data: { userId: context.userId ?? null, conversationId: context.conversationId ?? null, found: relevant.length > 0, notes: relevant } }; }

export async function runMemoryWriteTool(request: KernelRequest, context: KernelToolContext): Promise<KernelToolResult> { const notes = extractMemoryNotes(request.message); return { tool: 'memory.write', ok: notes.length > 0, summary: notes.length ? `Captured ${notes.length} memory candidate${notes.length === 1 ? '' : 's'} for future context.` : 'No durable memory candidate was detected.', data: { userId: context.userId ?? null, conversationId: context.conversationId ?? null, stored: false, storage: 'pending_memory_context', notes } }; }

export async function runTasksPlanTool(request: KernelRequest): Promise<KernelToolResult> { const content = request.message.trim(); return { tool: 'tasks.plan', ok: true, summary: 'Built a lightweight execution plan.', data: { steps: [`Understand the goal behind: "${content.slice(0, 80)}"`, 'Gather useful personal context from connected tools', 'Produce a clear action-oriented answer'] } }; }

export async function runNextActionTool(request: KernelRequest): Promise<KernelToolResult> { const text = lower(request.message); let nextAction = 'Clarify the goal and give the best next step.'; if (text.includes('gmail') || text.includes('email')) nextAction = 'Check Gmail connection and summarize the highest-value inbox signals.'; else if (text.includes('today') || text.includes('calendar')) nextAction = 'Combine today’s calendar with priorities into one practical plan.'; else if (text.includes('money') || text.includes('save')) nextAction = 'Identify the biggest savings opportunity first.'; else if (text.includes('build') || text.includes('create')) nextAction = 'Break the build into the first concrete implementation step.'; return { tool: 'productivity.next_action', ok: true, summary: 'Identified the best immediate next action.', data: { nextAction } }; }

export async function runCompareSmartTool(request: KernelRequest): Promise<KernelToolResult> { return { tool: 'compare.smart', ok: true, summary: 'Prepared a comparison frame for evaluating options.', data: { dimensions: ['cost', 'speed', 'quality', 'complexity', 'future-proofing'], prompt: request.message } }; }

export async function runFinanceAnalyzeTool(request: KernelRequest): Promise<KernelToolResult> { const text = lower(request.message); return { tool: 'finance.analyze', ok: true, summary: 'Analyzed the request for finance-related opportunities.', data: { category: text.includes('subscription') || text.includes('monthly') ? 'subscriptions' : text.includes('budget') || text.includes('save') ? 'budgeting' : 'general_finance', likelyOpportunity: text.includes('save') || text.includes('money') ? 'Potential savings opportunity detected.' : 'No strong finance pattern detected.' } }; }

export async function runGmailStatusTool(): Promise<KernelToolResult> { try { const payload = await callJson<GmailStatusPayload>('/api/integrations/gmail/status'); return { tool: 'gmail.status', ok: Boolean(payload.connected), summary: payload.connected ? `Gmail is connected${payload.lastSyncedAt ? ` and last synced at ${payload.lastSyncedAt}` : ''}.` : 'Gmail is not connected.', data: payload as Record<string, unknown> }; } catch (error) { return { tool: 'gmail.status', ok: false, summary: error instanceof Error ? error.message : 'Failed to check Gmail status.' }; } }

export async function runGmailInboxSummaryTool(): Promise<KernelToolResult> { try { const payload = await callJson<GmailStatusPayload>('/api/integrations/gmail/status'); const emailsAnalyzed = payload.emailsAnalyzed ?? 0; const summary = payload.summary || (payload.connected ? 'Gmail is connected, but no inbox summary has been synced yet.' : 'Connect Gmail to enable inbox summaries.'); return { tool: 'gmail.inbox_summary', ok: Boolean(payload.connected), summary, data: { connected: Boolean(payload.connected), status: payload.status ?? null, accountEmail: payload.accountEmail ?? null, lastSyncedAt: payload.lastSyncedAt ?? null, emailsAnalyzed, summary } }; } catch (error) { return { tool: 'gmail.inbox_summary', ok: false, summary: error instanceof Error ? error.message : 'Failed to summarize Gmail.' }; } }

export async function runGmailFinanceScanTool(): Promise<KernelToolResult> { try { const payload = await callJson<GmailStatusPayload>('/api/integrations/gmail/status'); const subscriptionsFound = payload.subscriptionsFound ?? 0; const recurringPaymentsFound = payload.recurringPaymentsFound ?? 0; const monthlyTotal = payload.monthlyTotal ?? 0; const estimatedMonthlySavings = payload.estimatedMonthlySavings ?? 0; const summary = payload.connected ? `Gmail finance scan: ${subscriptionsFound} subscriptions, ${recurringPaymentsFound} recurring payments, estimated monthly total ${monthlyTotal}, possible savings ${estimatedMonthlySavings}.` : 'Connect Gmail to scan receipts, renewals, subscriptions, and recurring payments.'; return { tool: 'gmail.finance_scan', ok: Boolean(payload.connected), summary, data: { connected: Boolean(payload.connected), subscriptionsFound, recurringPaymentsFound, monthlyTotal, estimatedMonthlySavings, lastSyncedAt: payload.lastSyncedAt ?? null, summary: payload.summary ?? '' } }; } catch (error) { return { tool: 'gmail.finance_scan', ok: false, summary: error instanceof Error ? error.message : 'Failed to run Gmail finance scan.' }; } }

export async function runCalendarStatusTool(): Promise<KernelToolResult> { try { const payload = await callJson<{ connected?: boolean; status?: string; accountEmail?: string | null; permissions?: string[]; errorMessage?: string | null }>('/api/integrations/google-calendar/status'); return { tool: 'calendar.status', ok: Boolean(payload.connected), summary: payload.connected ? 'Google Calendar is connected.' : 'Google Calendar is not connected.', data: { connected: Boolean(payload.connected), status: payload.status ?? null, accountEmail: payload.accountEmail ?? null, permissions: Array.isArray(payload.permissions) ? payload.permissions : [], errorMessage: payload.errorMessage ?? null } }; } catch (error) { return { tool: 'calendar.status', ok: false, summary: error instanceof Error ? error.message : 'Failed to check Google Calendar status.' }; } }

export async function runCalendarTodayTool(): Promise<KernelToolResult> { try { const payload = await callJson<{ events?: Array<Record<string, unknown>>; count?: number; calendarId?: string }>('/api/integrations/google-calendar/events?mode=today'); const events = Array.isArray(payload.events) ? payload.events : []; return { tool: 'calendar.today', ok: true, summary: events.length > 0 ? `Fetched ${events.length} event${events.length === 1 ? '' : 's'} for today.` : 'No events found for today.', data: { events, count: typeof payload.count === 'number' ? payload.count : events.length, calendarId: payload.calendarId ?? 'primary' } }; } catch (error) { return { tool: 'calendar.today', ok: false, summary: error instanceof Error ? error.message : 'Failed to fetch today’s calendar events.' }; } }

export async function runCalendarSearchTool(request: KernelRequest): Promise<KernelToolResult> { try { const window = inferSearchWindow(request.message); const query = new URLSearchParams(); if (window.timeMin) query.set('timeMin', window.timeMin); if (window.timeMax) query.set('timeMax', window.timeMax); query.set('maxResults', '50'); const payload = await callJson<{ events?: Array<Record<string, unknown>>; count?: number; calendarId?: string }>(`/api/integrations/google-calendar/events?${query.toString()}`); const events = Array.isArray(payload.events) ? payload.events : []; return { tool: 'calendar.search', ok: true, summary: events.length > 0 ? `Found ${events.length} calendar event${events.length === 1 ? '' : 's'}.` : 'No matching calendar events found.', data: { events, count: typeof payload.count === 'number' ? payload.count : events.length, calendarId: payload.calendarId ?? 'primary', timeMin: window.timeMin ?? null, timeMax: window.timeMax ?? null } }; } catch (error) { return { tool: 'calendar.search', ok: false, summary: error instanceof Error ? error.message : 'Failed to search calendar events.' }; } }

export async function runCalendarPlanDayTool(): Promise<KernelToolResult> { const today = await runCalendarTodayTool(); const events = Array.isArray(today.data?.events) ? today.data.events : []; const topEvents = events.slice(0, 5).map((event) => ({ title: String(event.summary || event.title || 'Untitled event'), start: event.start ?? null, end: event.end ?? null })); return { tool: 'calendar.plan_day', ok: today.ok, summary: today.ok ? `Prepared a day plan context from ${events.length} calendar event${events.length === 1 ? '' : 's'}.` : today.summary, data: { eventCount: events.length, topEvents, suggestions: events.length ? ['Protect focus time between calendar commitments.', 'Start with the highest-priority task before the next event.', 'Use open gaps for 25-minute execution blocks.'] : ['No calendar events found today. Use the first available block for the most important task.'] } }; }

export async function runCalendarCreateEventTool(request: KernelRequest): Promise<KernelToolResult> { const inferred = inferCreatePayload(request.message); if (!inferred.start || !inferred.end) return { tool: 'calendar.create_event', ok: false, summary: 'Could not infer event start and end time. Provide explicit ISO times.', data: inferred }; try { const payload = await callJson<{ success?: boolean; event?: Record<string, unknown> }>('/api/integrations/google-calendar/create', { method: 'POST', body: JSON.stringify({ title: inferred.title, start: inferred.start, end: inferred.end, description: inferred.description, location: inferred.location }) }); return { tool: 'calendar.create_event', ok: Boolean(payload.success), summary: payload.success ? 'Created calendar event successfully.' : 'Calendar event creation did not complete.', data: { event: payload.event ?? null } }; } catch (error) { return { tool: 'calendar.create_event', ok: false, summary: error instanceof Error ? error.message : 'Failed to create calendar event.', data: inferred }; } }

export async function runKernelTool(tool: KernelToolName, request: KernelRequest, context: KernelToolContext): Promise<KernelToolResult> { switch (tool) { case 'memory.search': return runMemorySearchTool(request, context); case 'memory.write': return runMemoryWriteTool(request, context); case 'tasks.plan': return runTasksPlanTool(request); case 'productivity.next_action': return runNextActionTool(request); case 'compare.smart': return runCompareSmartTool(request); case 'finance.analyze': return runFinanceAnalyzeTool(request); case 'gmail.status': return runGmailStatusTool(); case 'gmail.inbox_summary': return runGmailInboxSummaryTool(); case 'gmail.finance_scan': return runGmailFinanceScanTool(); case 'calendar.status': return runCalendarStatusTool(); case 'calendar.today': return runCalendarTodayTool(); case 'calendar.search': return runCalendarSearchTool(request); case 'calendar.create_event': return runCalendarCreateEventTool(request); case 'calendar.plan_day': return runCalendarPlanDayTool(); default: return { tool, ok: false, summary: `Unknown tool: ${tool}` }; } }
