'use client';

import { trackEvent } from '@/app/lib/analytics-client';
import type { AgentExecutionPayload, AgentResponseMetadata } from '@/types/agent-response';
import type { AgentName, AppState, ChatStreamEvent, Message } from '../app-store-types';
import { DEFAULT_ACTIVE_AGENT, nowIso } from '../app-store-state';
import { emitUsageUpdate, getConversationWindow, providerSafeErrorMessage, sortConversations, summarizePreview } from './chat-helpers';
import { deriveActiveStepsFromMetadata, mergeAgentMetadata, STREAM_STEP_EVENT_TYPES } from './chat-steps';

type SetState = (updater: (prev: AppState) => AppState) => void;
type GetState = () => AppState;
type Pace = 'fast' | 'normal' | 'careful' | 'deep';
type StreamAssistantResponseArgs = { requestId: string; assistantMessageId: string; conversationId: string; setState: SetState; getState: GetState };

function updateAssistantMessage(messages: Message[], assistantMessageId: string, updater: (message: Message) => Message): Message[] { return messages.map((message) => message.id === assistantMessageId ? updater(message) : message); }
function latestUserMessage(messages: Message[]) { return [...messages].reverse().find((msg) => msg.role === 'user')?.content ?? ''; }
function buildStreamPayload(messages: Message[], userId?: string) { return { message: latestUserMessage(messages), mode: 'agent', history: getConversationWindow(messages), userId: userId || 'system_anonymous' }; }
function safeObject(value: unknown): Record<string, unknown> | undefined { if (!value || typeof value !== 'object' || Array.isArray(value)) return undefined; return value as Record<string, unknown>; }
function safeArray(value: unknown): Array<Record<string, unknown>> | undefined { if (!Array.isArray(value)) return undefined; const items = value.filter((item) => item && typeof item === 'object') as Array<Record<string, unknown>>; return items.length ? items : undefined; }
function fallbackStepLabel(event: any) { if (event?.label) return String(event.label); if (event?.title) return String(event.title); if (event?.tool) { const tool = String(event.tool); if (tool === 'web_search') return 'Searching web'; if (tool === 'response_generator') return 'Generating response'; return `Using ${tool}`; } switch (event?.type) { case 'tool_started': return 'Using tool'; case 'tool_completed': return 'Tool completed'; case 'tool_failed': return 'Tool failed'; case 'thinking': return 'Thinking'; case 'status': return String(event?.status || 'Processing'); default: return 'Processing'; } }
function buildExecution(statusText: string, streamedText: string, toolCount = 0): AgentExecutionPayload { return { intent: 'general', forceMode: streamedText.trim() ? 'status' : 'thinking', statusText, toolCount }; }
function inferPace(prompt: string): Pace { const text = prompt.toLowerCase(); if (/quick|fast|lyhyt|nopea|short/.test(text)) return 'fast'; if (/why|analyze|suunnitelma|plan|strategy|tarkasti|deep|detail|architecture/.test(text)) return 'deep'; if (/help|stuck|confused|stress|vaikea|en tiedä|ongelma/.test(text)) return 'careful'; return 'normal'; }
function nextVisibleChunkLength(remaining: string, pace: Pace, visibleText: string) { if (visibleText.length < 120) return Math.min(remaining.length, pace === 'deep' ? 92 : 110); const newline = remaining.search(/\n\n|\n[-*•]|\n\d+\./); if (newline >= 0 && newline <= 120) return Math.max(1, newline + 1); const insight = remaining.search(/(Tärkein|Important|Best|Paras|Next|Seuraava|Recommendation|Suositus)/); if (insight >= 0 && insight <= 32) return Math.max(1, insight); const sentence = remaining.search(/[.!?](\s|$)/); if (sentence >= 0 && sentence <= 130) return Math.max(1, sentence + 1); const comma = remaining.search(/[,;:](\s|$)/); if (comma >= 24 && comma <= 90) return comma + 1; const min = pace === 'fast' ? 48 : pace === 'deep' ? 26 : 34; const max = pace === 'fast' ? 96 : pace === 'deep' ? 58 : 76; const space = remaining.slice(min, max).search(/\s/); if (space >= 0) return min + space + 1; return Math.min(remaining.length, pace === 'fast' ? 88 : pace === 'deep' ? 46 : 62); }
function nextFlushDelay(visibleText: string, lastChunk: string, pace: Pace) { if (!visibleText) return 0; const base = pace === 'fast' ? 14 : pace === 'deep' ? 38 : pace === 'careful' ? 34 : 24; if (/\n\n$/.test(lastChunk)) return pace === 'fast' ? 56 : 115; if (/(Tärkein|Important|Best|Paras|Next|Seuraava|Recommendation|Suositus)\s*$/i.test(lastChunk)) return 135; if (/[.!?]\s*$/.test(lastChunk)) return pace === 'fast' ? 46 : 88; if (/[,;:]\s*$/.test(lastChunk)) return pace === 'fast' ? 30 : 58; return base; }

export async function streamAssistantResponse({ requestId, assistantMessageId, conversationId, setState, getState }: StreamAssistantResponseArgs) {
  const currentState = getState(); const conversationMessages = currentState.messageState[conversationId] ?? []; const latestPrompt = latestUserMessage(conversationMessages); const pace = inferPace(latestPrompt); const payload = buildStreamPayload(conversationMessages, currentState.user?.id);
  setState((prev) => { const messages = prev.messageState[conversationId] ?? []; const execution = buildExecution('Thinking', '', 0); return { ...prev, activeAgent: DEFAULT_ACTIVE_AGENT, messageState: { ...prev.messageState, [conversationId]: updateAssistantMessage(messages, assistantMessageId, (message) => ({ ...message, isStreaming: true, content: '', structuredData: { execution }, agentMetadata: { ...mergeAgentMetadata(message.agentMetadata), execution, structuredData: { execution } } })) } }; });
  const response = await fetch('/api/agent', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) });
  if (!response.ok) { const reason = await response.json().catch(() => null); if (reason?.usage) emitUsageUpdate({ usage: reason.usage, plan: reason?.plan }); throw new Error(providerSafeErrorMessage(reason?.error || reason?.message || `Request failed (${response.status})`)); }
  const reader = response.body?.getReader(); if (!reader) throw new Error('Missing response stream.');
  const decoder = new TextDecoder(); let buffer = ''; let modelText = ''; let visibleText = ''; let streamComplete = false; let toolCount = 0; let flushTimer: number | null = null; let lastStatusText = 'Thinking'; let latestMetadata: AgentResponseMetadata | undefined; let latestToolResults: Array<Record<string, unknown>> | undefined; const startedAt = Date.now();
  const applyState = (content: string, statusText: string, metadata?: AgentResponseMetadata, toolResults?: Array<Record<string, unknown>>) => { setState((prev) => { const messages = prev.messageState[conversationId] ?? []; const execution = buildExecution(statusText, content, toolCount); const structuredData = { ...(safeObject(metadata?.structuredData) ?? {}), execution }; return { ...prev, activeSteps: deriveActiveStepsFromMetadata({ ...metadata, execution, structuredData }, prev.activeSteps), messageState: { ...prev.messageState, [conversationId]: updateAssistantMessage(messages, assistantMessageId, (message) => ({ ...message, content, isStreaming: !streamComplete, structuredData, toolResults, agentMetadata: { ...mergeAgentMetadata(message.agentMetadata), ...metadata, execution, structuredData } })) } }; }); };
  const clearFlushTimer = () => { if (flushTimer !== null) { window.clearTimeout(flushTimer); flushTimer = null; } };
  const scheduleFlush = (delay = 0) => { if (flushTimer !== null) return; flushTimer = window.setTimeout(() => { flushTimer = null; if (visibleText === modelText) return; const remaining = modelText.slice(visibleText.length); const len = nextVisibleChunkLength(remaining, pace, visibleText); const chunk = remaining.slice(0, Math.max(1, len)); visibleText += chunk; applyState(visibleText, lastStatusText, latestMetadata, latestToolResults); if (visibleText !== modelText) scheduleFlush(nextFlushDelay(visibleText, chunk, pace)); }, delay); };
  const flushAll = () => { clearFlushTimer(); visibleText = modelText; applyState(visibleText, lastStatusText, latestMetadata, latestToolResults); };
  const handleStepEvent = (event: any) => { const label = fallbackStepLabel(event); lastStatusText = label; if (event?.type === 'tool_started') toolCount += 1; trackEvent('chat_phase_transition', { conversationId, messageId: assistantMessageId, requestId, properties: { phase: event?.type, label } }); applyState(visibleText, label, latestMetadata, latestToolResults); };
  const handleEvent = (event: ChatStreamEvent | any) => { const type = event?.type; if (STREAM_STEP_EVENT_TYPES.has(type) || type === 'status' || type === 'log' || type === 'tool_started' || type === 'tool_completed' || type === 'tool_failed') { if (type !== 'log') handleStepEvent(event); return; } if (type === 'answer_delta' || type === 'delta') { const delta = event?.delta || event?.content || ''; if (!delta) return; modelText += delta; lastStatusText = 'Writing answer'; scheduleFlush(visibleText ? nextFlushDelay(visibleText, delta, pace) : 0); return; } if (type === 'answer_completed' || type === 'completed') { streamComplete = true; modelText = event?.content || modelText || 'No response generated.'; const metadataBase = (event?.metadata || {}) as AgentResponseMetadata; const eventStructuredData = safeObject(event?.structuredData); latestToolResults = safeArray(event?.toolResults); latestMetadata = { ...metadataBase, structuredData: { ...(safeObject(metadataBase?.structuredData) ?? {}), ...(eventStructuredData ?? {}) } } as AgentResponseMetadata; lastStatusText = 'Completed'; flushAll(); trackEvent('chat_stream_completed', { conversationId, messageId: assistantMessageId, requestId, properties: { ms: typeof event?.metrics?.completionMs === 'number' ? event.metrics.completionMs : Date.now() - startedAt, chars: typeof event?.metrics?.charCount === 'number' ? event.metrics.charCount : modelText.length, pace } }); return; } if (type === 'done') return; if (type === 'error') throw new Error(event?.error || event?.message || 'Streaming failed.'); };
  while (true) { const { done, value } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split('\n'); buffer = lines.pop() || ''; for (const line of lines) { if (!line.trim()) continue; try { handleEvent(JSON.parse(line) as ChatStreamEvent); } catch { } } }
  if (buffer.trim()) { try { handleEvent(JSON.parse(buffer) as ChatStreamEvent); } catch { } }
  if (!streamComplete) throw new Error('Streaming interrupted before completion.');
  setState((prev) => { const messages = prev.messageState[conversationId] ?? []; return { ...prev, conversationList: sortConversations(prev.conversationList.map((conversation) => conversation.id === conversationId ? { ...conversation, updatedAt: nowIso(), lastMessagePreview: summarizePreview(messages), messageCount: messages.length } : conversation)), agents: { ...prev.agents, [DEFAULT_ACTIVE_AGENT as AgentName]: { ...prev.agents[DEFAULT_ACTIVE_AGENT as AgentName], status: 'completed', lastRun: nowIso() } }, isAgentResponding: false, activeRequestId: null }; });
}
