import { useCallback, useEffect, useRef, useState, type Dispatch, type SetStateAction } from 'react';
import { useAppStore } from '@/app/store/app-store';
import type { MessageAttachment } from '@/app/store/app-store';

const NEAR_BOTTOM_THRESHOLD = 140;
const SCROLL_MEMORY_KEY = 'kivo-chat-scroll-memory-v1';
const MIN_SCROLL_SAFETY_SPACE = 28;
const MIN_COMPOSER_CLEARANCE = 178;
const MAX_KEYBOARD_OFFSET_RATIO = 0.62;
const MAX_KEYBOARD_OFFSET_ABSOLUTE = 430;

export type KivoChatNotice = { title: string; detail: string };
type SpeechRecognitionEventLike = Event & { results: ArrayLike<ArrayLike<{ transcript: string }>> };
type SpeechRecognitionLike = { continuous: boolean; interimResults: boolean; lang: string; start: () => void; stop: () => void; onresult: ((event: SpeechRecognitionEventLike) => void) | null; onerror: ((event: Event) => void) | null; onend: (() => void) | null };
declare global { interface Window { webkitSpeechRecognition?: new () => SpeechRecognitionLike; SpeechRecognition?: new () => SpeechRecognitionLike } }

type UseKivoChatScreenHooksParams = { activeConversationId: string; hasMessages: boolean; messagesLength: number; messagesLastRole?: string; lastMessageKey: string; isAgentResponding: boolean; isSending: boolean; attachmentsLength: number; draftPrompt: string; notice: KivoChatNotice | null; setNotice: (notice: KivoChatNotice | null) => void; setDraftPrompt: (value: string) => void; showNotice: (title: string, detail: string) => void; focusComposer: () => void };

export function useSidebarAutoToggle(hasMessages: boolean, setIsSidebarOpen: Dispatch<SetStateAction<boolean>>) { const previousHasMessagesRef = useRef(hasMessages); useEffect(() => { const previousHasMessages = previousHasMessagesRef.current; if (hasMessages && !previousHasMessages) setIsSidebarOpen(false); else if (!hasMessages && previousHasMessages) setIsSidebarOpen(true); previousHasMessagesRef.current = hasMessages; }, [hasMessages, setIsSidebarOpen]); }
export function useNoticeTimeout(notice: KivoChatNotice | null, setNotice: (notice: KivoChatNotice | null) => void) { const noticeTimeoutRef = useRef<number | null>(null); useEffect(() => { if (noticeTimeoutRef.current) { window.clearTimeout(noticeTimeoutRef.current); noticeTimeoutRef.current = null; } if (!notice) return; noticeTimeoutRef.current = window.setTimeout(() => { setNotice(null); noticeTimeoutRef.current = null; }, 2400); return () => { if (noticeTimeoutRef.current) { window.clearTimeout(noticeTimeoutRef.current); noticeTimeoutRef.current = null; } }; }, [notice, setNotice]); }

function clampKeyboardOffset(rawOffset: number) { if (typeof window === 'undefined') return Math.max(0, rawOffset); const viewportHeight = window.visualViewport?.height ?? window.innerHeight; const maxByViewport = Math.round(viewportHeight * MAX_KEYBOARD_OFFSET_RATIO); const maxOffset = Math.max(260, Math.min(MAX_KEYBOARD_OFFSET_ABSOLUTE, maxByViewport)); if (!Number.isFinite(rawOffset)) return 0; return Math.max(0, Math.min(Math.round(rawOffset), maxOffset)); }
function isEditableElement(value: EventTarget | null) { if (!(value instanceof HTMLElement)) return false; const tag = value.tagName.toLowerCase(); return tag === 'textarea' || tag === 'input' || value.isContentEditable; }
function getKeyboardOffsetFromViewport(baselineHeight: number, forceFocused = false) { if (typeof window === 'undefined') return 0; const viewport = window.visualViewport; const layoutHeight = window.innerHeight; const visualHeight = viewport?.height ?? layoutHeight; const rawVisualOffset = viewport ? layoutHeight - viewport.height - viewport.offsetTop : 0; const rawBaselineOffset = baselineHeight > 0 ? baselineHeight - visualHeight : 0; const focused = forceFocused || isEditableElement(document.activeElement); if (!focused) return 0; const rawOffset = Math.max(rawVisualOffset, rawBaselineOffset, 0); if (rawOffset < 72) return 0; return clampKeyboardOffset(rawOffset); }

export function useKivoChatScreenHooks({ activeConversationId, hasMessages, messagesLength, messagesLastRole, lastMessageKey, isAgentResponding, isSending, attachmentsLength, draftPrompt, notice, setNotice, setDraftPrompt, showNotice, focusComposer }: UseKivoChatScreenHooksParams) {
  const recognitionRef = useRef<SpeechRecognitionLike | null>(null);
  const mainScrollRef = useRef<HTMLDivElement | null>(null);
  const lastMessageCountRef = useRef(0);
  const isNearBottomRef = useRef(true);
  const scrollMemoryRef = useRef<Record<string, number>>({});
  const [showScrollToLatest, setShowScrollToLatest] = useState(false);
  const [keyboardOffset, setKeyboardOffset] = useState(0);
  const [bottomOverlayInset, setBottomOverlayInset] = useState(0);
  const scrollTickingRef = useRef(false);
  const composerDockRef = useRef<HTMLDivElement | null>(null);
  const attachmentTrayRef = useRef<HTMLDivElement | null>(null);
  const viewportSyncFrameRef = useRef<number | null>(null);
  const baselineViewportHeightRef = useRef(0);
  const [isListening, setIsListening] = useState(false);

  useNoticeTimeout(notice, setNotice);

  const measureBottomOverlayInset = useCallback(() => { if (typeof window === 'undefined') return; const viewportBottom = window.visualViewport ? window.visualViewport.height + window.visualViewport.offsetTop : window.innerHeight; const scrollerBottom = mainScrollRef.current?.getBoundingClientRect().bottom ?? viewportBottom; const measurementBottom = Math.min(viewportBottom, scrollerBottom); const nodes = [composerDockRef.current, attachmentTrayRef.current].filter((node): node is HTMLElement => Boolean(node)); const nextInset = nodes.reduce((maxInset, node) => { const rect = node.getBoundingClientRect(); if (rect.height <= 0 || rect.width <= 0) return maxInset; return Math.max(maxInset, Math.max(0, measurementBottom - rect.top)); }, 0); setBottomOverlayInset((current) => Math.abs(current - nextInset) < 1 ? current : nextInset); }, []);
  const persistScrollMemory = useCallback(() => { if (typeof window === 'undefined') return; window.sessionStorage.setItem(SCROLL_MEMORY_KEY, JSON.stringify(scrollMemoryRef.current)); }, []);
  const updateScrollState = useCallback(() => { const scroller = mainScrollRef.current; if (!scroller) return; const distanceFromBottom = scroller.scrollHeight - (scroller.scrollTop + scroller.clientHeight); const nearBottom = distanceFromBottom <= NEAR_BOTTOM_THRESHOLD; isNearBottomRef.current = nearBottom; setShowScrollToLatest(!nearBottom && hasMessages); scrollMemoryRef.current[activeConversationId] = Math.max(distanceFromBottom, 0); }, [activeConversationId, hasMessages]);
  const scrollToLatest = useCallback((behavior: ScrollBehavior = 'smooth') => { const scroller = mainScrollRef.current; if (!scroller) return; scroller.scrollTo({ top: scroller.scrollHeight, behavior }); }, []);

  useEffect(() => { if (typeof window === 'undefined') return; try { const raw = window.sessionStorage.getItem(SCROLL_MEMORY_KEY); if (!raw) return; const parsed = JSON.parse(raw) as Record<string, number>; if (parsed && typeof parsed === 'object') scrollMemoryRef.current = parsed; } catch { scrollMemoryRef.current = {}; } }, []);

  useEffect(() => { if (typeof window === 'undefined') return; baselineViewportHeightRef.current = Math.max(window.innerHeight, window.visualViewport?.height ?? 0); const applyKeyboardOffset = (forceFocused = false) => { const nextOffset = getKeyboardOffsetFromViewport(baselineViewportHeightRef.current, forceFocused); setKeyboardOffset((current) => Math.abs(current - nextOffset) < 1 ? current : nextOffset); measureBottomOverlayInset(); }; const syncKeyboardOffset = (forceFocused = false) => { if (viewportSyncFrameRef.current !== null) window.cancelAnimationFrame(viewportSyncFrameRef.current); viewportSyncFrameRef.current = window.requestAnimationFrame(() => { viewportSyncFrameRef.current = null; applyKeyboardOffset(forceFocused); }); }; const handleFocusIn = (event: FocusEvent) => { if (!isEditableElement(event.target)) return; window.setTimeout(() => syncKeyboardOffset(true), 40); window.setTimeout(() => syncKeyboardOffset(true), 160); window.setTimeout(() => syncKeyboardOffset(true), 320); }; const handleFocusOut = () => { window.setTimeout(() => syncKeyboardOffset(false), 40); window.setTimeout(() => syncKeyboardOffset(false), 180); }; const handleWindowResize = () => { if (!isEditableElement(document.activeElement)) baselineViewportHeightRef.current = Math.max(window.innerHeight, window.visualViewport?.height ?? 0); syncKeyboardOffset(false); measureBottomOverlayInset(); }; const handleViewportChange = () => syncKeyboardOffset(false); applyKeyboardOffset(false); const resizeObserver = new ResizeObserver(() => measureBottomOverlayInset()); if (composerDockRef.current) resizeObserver.observe(composerDockRef.current); if (attachmentTrayRef.current) resizeObserver.observe(attachmentTrayRef.current); window.visualViewport?.addEventListener('resize', handleViewportChange); window.visualViewport?.addEventListener('scroll', handleViewportChange); window.addEventListener('resize', handleWindowResize); window.addEventListener('focusin', handleFocusIn); window.addEventListener('focusout', handleFocusOut); return () => { if (viewportSyncFrameRef.current !== null) { window.cancelAnimationFrame(viewportSyncFrameRef.current); viewportSyncFrameRef.current = null; } resizeObserver.disconnect(); window.visualViewport?.removeEventListener('resize', handleViewportChange); window.visualViewport?.removeEventListener('scroll', handleViewportChange); window.removeEventListener('resize', handleWindowResize); window.removeEventListener('focusin', handleFocusIn); window.removeEventListener('focusout', handleFocusOut); }; }, [measureBottomOverlayInset]);
  useEffect(() => { measureBottomOverlayInset(); }, [attachmentsLength, draftPrompt, keyboardOffset, measureBottomOverlayInset]);
  useEffect(() => { if (!mainScrollRef.current) return; if (isNearBottomRef.current) { requestAnimationFrame(() => { scrollToLatest('auto'); updateScrollState(); }); return; } updateScrollState(); }, [bottomOverlayInset, scrollToLatest, updateScrollState]);
  useEffect(() => { const scroller = mainScrollRef.current; if (!scroller) return; const handleScroll = () => { if (scrollTickingRef.current) return; scrollTickingRef.current = true; requestAnimationFrame(() => { updateScrollState(); scrollTickingRef.current = false; }); }; scroller.addEventListener('scroll', handleScroll, { passive: true }); updateScrollState(); return () => { scroller.removeEventListener('scroll', handleScroll); scrollTickingRef.current = false; updateScrollState(); persistScrollMemory(); }; }, [persistScrollMemory, updateScrollState]);
  useEffect(() => { const scroller = mainScrollRef.current; if (!scroller) return; const preservedDistance = scrollMemoryRef.current[activeConversationId]; requestAnimationFrame(() => { if (typeof preservedDistance === 'number' && Number.isFinite(preservedDistance)) scroller.scrollTop = Math.max(0, scroller.scrollHeight - scroller.clientHeight - preservedDistance); else scroller.scrollTop = scroller.scrollHeight; updateScrollState(); }); lastMessageCountRef.current = messagesLength; }, [activeConversationId, messagesLength, updateScrollState]);
  useEffect(() => { const messageCountChanged = messagesLength !== lastMessageCountRef.current; const shouldFollow = isNearBottomRef.current || (messageCountChanged && messagesLastRole === 'user'); if (!shouldFollow) { lastMessageCountRef.current = messagesLength; return; } const behavior: ScrollBehavior = messageCountChanged ? 'smooth' : 'auto'; requestAnimationFrame(() => { scrollToLatest(behavior); updateScrollState(); }); lastMessageCountRef.current = messagesLength; }, [isAgentResponding, isSending, lastMessageKey, messagesLastRole, messagesLength, scrollToLatest, updateScrollState]);

  const ensureSpeechRecognition = useCallback(() => { if (recognitionRef.current) return recognitionRef.current; const SpeechRecognitionCtor = typeof window !== 'undefined' ? window.SpeechRecognition || window.webkitSpeechRecognition : null; if (!SpeechRecognitionCtor) return null; const recognition = new SpeechRecognitionCtor(); recognition.continuous = false; recognition.interimResults = false; recognition.lang = 'en-US'; recognition.onresult = (event) => { const transcript = event.results?.[0]?.[0]?.transcript?.trim(); if (!transcript) return; const currentDraft = typeof useAppStore.getState === 'function' ? useAppStore.getState().draftPrompt : draftPrompt; setDraftPrompt(currentDraft ? `${currentDraft} ${transcript}` : transcript); focusComposer(); }; recognition.onerror = () => { setIsListening(false); showNotice('Speech unavailable', 'Microphone input could not be captured.'); }; recognition.onend = () => setIsListening(false); recognitionRef.current = recognition; return recognition; }, [draftPrompt, focusComposer, setDraftPrompt, showNotice]);
  const toggleMic = useCallback(() => { const recognition = ensureSpeechRecognition(); if (!recognition) { showNotice('Speech unavailable', 'This browser does not support speech recognition.'); return; } if (isListening) { recognition.stop(); setIsListening(false); return; } setIsListening(true); recognition.start(); }, [ensureSpeechRecognition, isListening, showNotice]);

  const composerClearance = Math.max(MIN_COMPOSER_CLEARANCE, Math.round(bottomOverlayInset + MIN_SCROLL_SAFETY_SPACE));
  const scrollBottomPadding = 0;
  const lastMessageSafetySpacer = composerClearance;
  const latestButtonBottom = Math.max(12, Math.round(bottomOverlayInset + MIN_SCROLL_SAFETY_SPACE));
  return { isListening, keyboardOffset, scrollBottomPadding, lastMessageSafetySpacer, latestButtonBottom, showScrollToLatest, mainScrollRef, composerDockRef, attachmentTrayRef, scrollToLatest, updateScrollState, toggleMic };
}

export function cleanupAttachments(items: MessageAttachment[]) { items.forEach((attachment) => { if (attachment.previewUrl) URL.revokeObjectURL(attachment.previewUrl); }); }
export function buildAttachment(file: File): MessageAttachment { return { id: `${Date.now()}-${Math.random().toString(16).slice(2)}`, name: file.name, size: file.size, mimeType: file.type || 'application/octet-stream', kind: file.type.startsWith('image/') ? 'image' : 'file', previewUrl: file.type.startsWith('image/') ? URL.createObjectURL(file) : undefined }; }
